spring.application.name=api-gateway
server.port=5555


# auth Service
spring.cloud.gateway.server.webflux.routes[0].id=authservice-api
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**
spring.cloud.gateway.server.webflux.routes[0].filters[0]=RewritePath=/auth/?(?<segment>.*), /${segment}

#MICROSERVICE-1 service
spring.cloud.gateway.server.webflux.routes[1].id=microservice1-api
spring.cloud.gateway.server.webflux.routes[1].uri=lb://MICROSERVICE-1
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/micro1/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=RewritePath=/micro1/?(?<segment>.*), /${segment}